name: Run flake8 against codebase ⚙️

on: [push, pull_request]

jobs:
  run_flake8:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      name: Set up Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install flake8 📦
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Run flake8 ⚙️
      run: |
        flake8 .
